export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FIRST_FETCH_NEWS_REQUEST = 'FIRST_FETCH_NEWS_REQUEST';
